services:
  postgres:
    image: postgres:13.16
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: universalfitness
      POSTGRES_USER: universalfitness
      POSTGRES_PASSWORD: universalfitness
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U universalfitness -h localhost
      interval: 1s
  s3:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    command: server /data --console-address ":9001"
    ports:
      - "${S3_PORT}:9000"
      - "127.0.0.1:26546:9001"
    environment:
      MINIO_ROOT_USER: universalfitness
      MINIO_ROOT_PASSWORD: universalfitness
    volumes:
      - ./data/s3:/data
  pgweb:
    image: sosedoff/pgweb:0.16.2
    ports:
      - "127.0.0.1:${PGWEB_PORT}:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://universalfitness:universalfitness@postgres:5432/universalfitness?sslmode=disable
      PGWEB_LOCK_SESSION: true
    depends_on:
      postgres:
        condition: service_healthy
