services:
  postgres:
    image: postgres:13.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: universalfitness
      POSTGRES_USER: universalfitness
      POSTGRES_PASSWORD: universalfitness
    volumes:
      - pgdata:/var/lib/postgresql/data
  s3:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: universalfitness
      MINIO_ROOT_PASSWORD: universalfitness
    volumes:
      - s3data:/data
  pgweb:
    image: sosedoff/pgweb:0.16.2
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://universalfitness:universalfitness@postgres:5432/universalfitness?sslmode=disable
      PGWEB_LOCK_SESSION: true
    depends_on:
      - postgres

volumes:
  pgdata:
  s3data:
